### ISSUE TITLE
关于数据集组织的问题

### ISSUE THREAD

**Issue by zhilanyue** [yxgeee/OpenIBL#11]
你好！
在复现你的代码的时候，执行sfrs训练（./scripts/train_sfrs_dist.sh）遇到了这样的问题：
![QQ截图20201217161354](https://user-images.githubusercontent.com/55051595/102460786-794dcc80-4082-11eb-9586-caa17c911c17.png)
问题出在(https://github.com/yxgeee/OpenIBL/blob/5ab80d65afa42ca22210c4c08983fdc156696bab/ibl/utils/data/sampler.py#L85)

在采样器中输出发现训练集的pos_list\neg_list是一样的：
https://github.com/yxgeee/OpenIBL/blob/5ab80d65afa42ca22210c4c08983fdc156696bab/ibl/utils/data/sampler.py#L32
https://github.com/yxgeee/OpenIBL/blob/5ab80d65afa42ca22210c4c08983fdc156696bab/ibl/utils/data/sampler.py#L33
![QQ截图20201217161459](https://user-images.githubusercontent.com/55051595/102460868-91255080-4082-11eb-91aa-c9edddce5504.png)
修改过dataset.py中近邻搜索方法搜索半径，问题依然存在
https://github.com/yxgeee/OpenIBL/blob/5ab80d65afa42ca22210c4c08983fdc156696bab/ibl/utils/data/dataset.py#L28

我的数据集组织情况如下，
![QQ截图20201217161522](https://user-images.githubusercontent.com/55051595/102463444-0f372680-4086-11eb-900e-2d73ceebc8b4.png)
想请教一下问题所在，谢谢！

**Comment by yxgeee** [comment]
`neg_list`存的是25m以内的图，然后在sampler里会针对每个anchor的neg_list找到25m以外的negative pair，参见https://github.com/yxgeee/OpenIBL/blob/master/ibl/utils/data/sampler.py#L79

**Comment by zhilanyue** [comment]
> `neg_list`存的是25m以内的图，然后在sampler里会针对每个anchor的neg_list找到25m以外的negative pair，参见https://github.com/yxgeee/OpenIBL/blob/master/ibl/utils/data/sampler.py#L79

了解，感谢！
