### ISSUE TITLE
mean and std of image transform

### ISSUE THREAD

**Issue by amaralibey** [yxgeee/OpenIBL#15]
Hello,
I was wondering how did the mean and std of the transform come from ? I've calculated that of Pittsburg and it seem way different, especially the std !
https://github.com/yxgeee/OpenIBL/blob/5ab80d65afa42ca22210c4c08983fdc156696bab/ibl/utils/data/__init__.py#L37

```
mean=[0.48501960784313836, 0.4579568627450961, 0.4076039215686255],

std=[0.00392156862745098, 0.00392156862745098, 0.00392156862745098]
```

The std is way too small, can you please explain how did you get to it ?
Thanks

**Comment by yxgeee** [comment]
The mean and std are borrowed from the VGG pre-training weights of MatConvNet (it should be computed on ImageNet), since the official repos of NetVLAD and SARE are based on MatConvNet. To reproduce their results, we need to load the same pretrained weights as well as the same mean/std.
