### ISSUE TITLE
Other Models

### ISSUE THREAD

**Issue by michaelschleiss** [yxgeee/OpenIBL#16]
I planned to integrate more models (feature extractors) apart from vgg16 into your library and then saw in some of your code comments some artifacts about resnet. Are you planning to integrate those other models in the future and if you have already done so privately are there any insights about the effects of others models that you could share?

**Comment by yxgeee** [comment]
Yes, I have tried to use ResNet with NetVLAD but unfortunately, I achieved poor results. So I did not release this model in the library. I am also wondering if other architectures could achieve better results than VGG when using the NetVLAD layer. When testing ResNet, I found that 1) a deeper one does not necessarily lead to better results, and 2) a larger resolution of feature maps fed into NetVLAD leads to better results.
