### ISSUE TITLE
Question on tab.3 of the paper

### ISSUE THREAD

**Issue by XiSHEN0220** [yxgeee/OpenIBL#19]
Hi, thanks for sharing your nice work!!!

Looking into the paper, I realise that it also includes comparaisons on Oxford and Paris.  
As I know, there are other approaches report better performances on these benchmarks, such as : [Fine-tuning CNN Image Retrieval with No Human Annotation](https://arxiv.org/pdf/1711.02512.pdf). 
They report **87.8** in terms of mAP on Oxford. 

I am wondering whether there are particular reasons that these two lines of research are not comparable. 

Thanks in advance, 

Best

**Comment by yxgeee** [comment]
We did not train on these retrieval datasets (e.g. Oxford, Paris). We just show the generalization ability of our model by directly testing it. The same protocol was used by NetVLAD and SARE. 

The one you mentioned, as well as the other works that focused on image retrieval, trained and tested their models on the same retrieval datasets. Thus they are not comparable with our methods.

**Comment by XiSHEN0220** [comment]
Thanks for your reply. :) 
I close the issue.
