### ISSUE TITLE
.mat files

### ISSUE THREAD

**Issue by Shmnl** [yxgeee/OpenIBL#23]
Hello Yixiao,

I want to ask how can I generate mat files for Pittsburgh dataset?

> examples/data
> ├── pitts
> │   ├── raw
> │   │   ├── pitts250k_test.mat
> │   │   ├── pitts250k_train.mat
> │   │   ├── pitts250k_val.mat
> │   │   ├── pitts30k_test.mat
> │   │   ├── pitts30k_train.mat
> │   │   ├── pitts30k_val.mat

Thanks.

**Comment by bobo7727** [comment]
Hello，
I have some questions to ask.
How to organize the dataset pitts/tokyo for testing and trainning? 
what the dateset organizational structure is. Should I just unzip all the pictures of the dataset and copy them together under the pitts and tokyo folder?

**Comment by yxgeee** [comment]
> Hello Yixiao,
> 
> I want to ask how can I generate mat files for Pittsburgh dataset?
> 
> > examples/data
> > ├── pitts
> > │   ├── raw
> > │   │   ├── pitts250k_test.mat
> > │   │   ├── pitts250k_train.mat
> > │   │   ├── pitts250k_val.mat
> > │   │   ├── pitts30k_test.mat
> > │   │   ├── pitts30k_train.mat
> > │   │   ├── pitts30k_val.mat
> 
> Thanks.

The mat files were downloaded directly from the authors' dataset links. I have uploaded the mat files at https://drive.google.com/drive/folders/1cP2_jXlJd_sGSOYB5wCLGVnAdQSdqTOd?usp=sharing.

**Comment by yxgeee** [comment]
> Hello，
> I have some questions to ask.
> How to organize the dataset pitts/tokyo for testing and trainning?
> what the dateset organizational structure is. Should I just unzip all the pictures of the dataset and copy them together under the pitts and tokyo folder?

@bobo7727 Please refer to https://github.com/yxgeee/OpenIBL/blob/master/docs/INSTALL.md#datasets
