### ISSUE TITLE
Question about NetVLAD in MODEL_ZOO.md

### ISSUE THREAD

**Issue by rann1018** [yxgeee/OpenIBL#3]
Hi, @yxgeee 
Thanks a lot for sharing this valuable image-based localization tool.
I would like to re-rank the retrieval results based on your work.
In MODEL_ZOO.md,  I only find SFRS and SARE models but miss NetVLAD model.
Where could I download the pretrained NetVLAD model?
Thanks a  lot for your help.

**Comment by yxgeee** [comment]
Hi, here is the NetVLAD model reproduced by `OpenIBL`:
https://drive.google.com/drive/folders/1sjsxnlqyUCjrXOg2ahwrf7WufU1jvO_D?usp=sharing

**Comment by rann1018** [comment]
Thanks a lot for your quick reply. 
May I ask another question?
When I extract descriptor for a single image, How can I change  
different pretrained models with  'torch.hub.load()'?
Thanks for your help.

**Comment by yxgeee** [comment]
I have only uploaded the best model (trained by SFRS) for `torch.hub`, I will upload both SARE's and NetVLAD's if required.

**Comment by rann1018** [comment]
Fine,
Thanks a lot for your help and your work.
