### ISSUE TITLE
Is the pretrained model also MIT?

### ISSUE THREAD

**Issue by IshitaTakeshi** [yxgeee/OpenIBL#36]
Seeing the line [test_tokyo_best.py#L42](https://github.com/yxgeee/OpenIBL/blob/master/examples/test_tokyo_best.py#L42), the pretrained model is downloaded from the URL below.

https://github.com/yxgeee/OpenIBL/releases/download/v0.1.0-beta/vgg16_netvlad.pth

Is the pretained model also distributed under MIT? If so, I would like to use it with the appropriate citation.

**Comment by yxgeee** [comment]
Yes.

**Comment by IshitaTakeshi** [comment]
Thank you!
