### ISSUE TITLE
Question about CRN implementation.

### ISSUE THREAD

**Issue by rann1018** [yxgeee/OpenIBL#4]
Hi, @yxgeee 
I read your ECCV-2020 spotlight paper, and I notice that 
you compare with three methods: NetVLAD, SARE and **CRN**.
I would like to know if OpenIBL will implement  **CRN**  in the future.
Thanks a lot for your help.

**Comment by yxgeee** [comment]
I have no plan for the implementation of CRN currently.

**Comment by rann1018** [comment]
Fine,
Thank you for your reply.
