### ISSUE TITLE
How to get Image Description 

### ISSUE THREAD

**Issue by Akashchougule211** [yxgeee/OpenIBL#8]
I want input as image and output as Place name or image description

**Comment by yxgeee** [comment]
Please refer to https://github.com/yxgeee/OpenIBL#extract-descriptor-for-a-single-image for how to extract image descriptor for a single input image.

**Comment by Akashchougule211** [comment]
I have to refer this link but this only show numeric value not show image description

**Comment by yxgeee** [comment]
Yes, here we denote feature vectors as image descriptors. So what do you want? Image caption?

**Comment by Akashchougule211** [comment]
Yes ,I want image caption like only place name

**Comment by yxgeee** [comment]
You need to establish a gallery with images and their corresponding place name. Then using our code for feature extraction and image retrieval. At last, the place name of ranked top-1 gallery image can be used for describing the probe image.

**Comment by Akashchougule211** [comment]
Thank you sir for your response. This greatly helps.
